import './globals.css'

export const metadata = {
	title: "Artyom's Links | All links are there!",
	description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
}
